## [環境建置]

In [25]:
# -*- coding: utf-8 -*-
from platform import python_version
import os, time, socket

print("【日期時間】{}".format(time.strftime("%Y/%m/%d %H:%M:%S")))
print("【工作目錄】{}".format(os.getcwd()))
print("【主機名稱】{} ({})".format(socket.gethostname(),socket.gethostbyname(socket.gethostname())))
print("【Python】{}".format(python_version()))

%autosave 120

【日期時間】2021/04/18 00:26:00
【工作目錄】/Users/sky/Documents/GitHub/ML100Days/howework
【主機名稱】Skyde-MacBook-Air.local (127.0.0.1)
【Python】3.8.5


Autosaving every 120 seconds


In [ ]:
import numpy as np

In [5]:
!pip install --upgrade np

  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13651 sha256=192522afeba11acfb6c235ef59629017ea2a79d4eac7c612fabfe4c29043f001
  Stored in directory: /Users/sky/Library/Caches/pip/wheels/44/c8/fa/6341ec15fc1b7f1d7813744425e23817719133e2e6d2da01c9
Successfully built np


In [30]:
print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/envs/Py38/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2


In [13]:
a = np.arange(15).reshape(3,5)
print(a)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [15]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

2
(3, 5)
15
int64
8


In [22]:
print(list(a))
#----------
a.tolist()

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

1.  [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？


In [32]:

print('list(a)只會第一層型態轉換為list: ', list(a))
print('tolist()多層型態轉換為list: ', a.tolist())

list(a)只會第一層型態轉換為list:  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist()多層型態轉換為list:  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


2.   請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

In [56]:
a = np.random.randint(10, size=6)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)    # 陣列中的資料型態
print(a.itemsize)
print(len(a))
print(type)
"""
                                           
"""
b = np.random.randint(10, size=(3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))
#-------------------------------------------
c = np.random.randint(10, size=(2,3,2))
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[6 6 5 5 9 1]
1
(6,)
6
int64
8
6
<class 'type'>
[[9 6 6 9]
 [4 3 7 4]
 [1 6 8 8]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>
[[[2 4]
  [0 8]
  [6 6]]

 [[8 8]
  [7 2]
  [6 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>
