In [34]:
import math  
'math.pi = {0.pi}'.format(math)

'math.pi = 3.141592653589793'

In [24]:

from platform import python_version
import os, time, socket
import numpy as np

#from time import localtime
print('【日期時間】{0}'.format(time.strftime("%Y-%m-%d %H:%M:%S")))
print('【工作目錄】{}'.format(os.getcwd()))
print("【主機名稱】{1} ({0})".format(socket.gethostname(),socket.gethostbyname(socket.gethostname())))
print("【Python】{}".format(python_version()))


【日期時間】2021-05-24 13:09:15
【工作目錄】/Users/sky/Documents/GitHub/ML100Days/homework
【主機名稱】127.0.0.1 (Skyde-MacBook-Air.local)
【Python】3.8.8


numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

- object：必填，任何 array_like 物件
- dtype：指定轉成陣列後的元素型態
- copy：預設為 True，是否產生一個新的物件
- order：指定元素在記憶體中的儲存方式

In [6]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array({0: 123, 1: 456})
# array({0: 123, 1: 456})
np.array(list({0: 123, 1: 456}.items()))

array([[  0, 123],
       [  1, 456]])

In [57]:
print(np.zeros((2, 3), dtype = int))
# 建立由 0 組成的 2x3 陣列
print(np.ones((2, 3)))
# 建立由 1 組成的 2x3 陣列
print(np.full((2, 3), 168))
# 建立由 9 組成的 2x3 陣列

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[168 168 168]
 [168 168 168]]


In [84]:
print(np.zeros((2, 3)))
#
np.empty((2,3))
#使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定


[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
print(np.arange(1,10,2)) # 不包含尾數 (固定長度等差序列)
print(np.linspace(1,10,2, dtype=int))  # 包含尾數(固定區間等差序列)
np.logspace(0,2) # 返回對數分佈(等比序列)

[1 3 5 7 9]
[ 1 10]


array([  1.        ,   1.09854114,   1.20679264,   1.32571137,
         1.45634848,   1.59985872,   1.75751062,   1.93069773,
         2.12095089,   2.32995181,   2.55954792,   2.8117687 ,
         3.0888436 ,   3.39322177,   3.72759372,   4.09491506,
         4.49843267,   4.94171336,   5.42867544,   5.96362332,
         6.55128557,   7.19685673,   7.90604321,   8.68511374,
         9.54095476,  10.48113134,  11.51395399,  12.64855217,
        13.89495494,  15.26417967,  16.76832937,  18.42069969,
        20.23589648,  22.22996483,  24.42053095,  26.82695795,
        29.47051703,  32.37457543,  35.56480306,  39.06939937,
        42.9193426 ,  47.14866363,  51.79474679,  56.89866029,
        62.50551925,  68.6648845 ,  75.43120063,  82.86427729,
        91.0298178 , 100.        ])

In [79]:
from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2)) #標準常態分佈
random = rng.random((3,2)) #隨機分佈
integers = rng.integers(0, 10, size=(3,2))
print(normal)
print(random)
print(integers)

[[ 1.14450577 -0.23623407]
 [ 0.44277411 -0.04739682]
 [ 0.68499295  0.12914291]]
[[0.24430783 0.94805474]
 [0.83147829 0.20366023]
 [0.94656033 0.68596358]]
[[5 7]
 [3 3]
 [0 1]]


In [80]:
integers = rng.integers(0, 10, size=(3,2))
print(integers)

[[0 0]
 [8 1]
 [5 3]]



[簡答題] 
1. 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [91]:
#np.zeros(): 可以依照傳入的形狀引數，建立元素全為 0的陣列
print(np.zeros((3,3)))

#np.empty(): 不避設定起始值,但是可以建立給定形狀的陣列，元素值則會隨機給定。
print(np.empty((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [144]:

a = rng.random((2, 3))
print(a)

b = np.array(a, dtype = 'int8')
print(b.round())

[[0.35422093 0.29917866 0.36156553]
 [0.6679192  0.23280279 0.73288962]]
[[0 0 0]
 [0 0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [157]:
# 使用 linspace 函數，產生固定區間的陣列
m = 20 
n= 40
a = np.linspace(m,n, 6)
print(a)

[20. 24. 28. 32. 36. 40.]
