In [8]:
#from platform import python_version
#import os, time, socket

print("【日期時間】{}".format(time.strftime("%Y/%m/%d %H:%M:%S")))
print("【工作目錄】{}".format(os.getcwd()))
print("【主機名稱】{} ({})".format(socket.gethostname(),socket.gethostbyname(socket.gethostname())))
print("【Python】{}".format(python_version()))

【日期時間】2024/09/28 14:30:05
【工作目錄】/Users/sky/Documents/GitHub/ML100Days/homework
【主機名稱】Skyde-MacBook-Air.local (127.0.0.1)
【Python】3.8.16


In [ ]:
# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

In [ ]:
### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
可能有三種層級的函式,一樣結果
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



- a.sum()為a物件總和
- np.sum(a)為np package使用
- sum(a)加總a

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [5]:
# 記得先 Import 正確的套件
import numpy as np
A = np.arange(25).reshape(5,5)
print(A)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [48]:
# 正規化為轉換[0,1] 
A = np.random.random((5,5))
print(A)
B = (A- A.min())/(A.max()-A.min())
B

[[0.26564477 0.19301927 0.38560945 0.13254544 0.94347969]
 [0.89645123 0.37205113 0.62861212 0.98839149 0.23394005]
 [0.8821434  0.85444327 0.69513468 0.74086641 0.09760763]
 [0.17622133 0.79160635 0.80574672 0.64850083 0.35971449]
 [0.8499539  0.91378248 0.30933817 0.10292876 0.23755767]]


array([[0.18863963, 0.10710976, 0.32331279, 0.03922141, 0.9495817 ],
       [0.89678724, 0.30809213, 0.59610924, 1.        , 0.15304769],
       [0.88072517, 0.84962883, 0.67078792, 0.72212667, 0.        ],
       [0.08825226, 0.77908766, 0.79496175, 0.61843644, 0.29424293],
       [0.84458903, 0.91624342, 0.23769014, 0.00597353, 0.15710885]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [79]:
import  numpy.random as rng
A = rng.randint(1,10,10)
print(A)
B = []
for i in A:
  if i == A.max():
    B.append(-i)
  else:
    B.append(i)
B

[2 4 7 3 6 4 7 8 1 8]


[2, 4, 7, 3, 6, 4, 7, -8, 1, -8]